### ISSUE TITLE
install-spark with -x for 1.2.0.a does not set spark.default.parallelism correctly

### ISSUE THREAD

**Issue by jonchase** [awslabs/emr-bootstrap-actions#38]
When I run s3://support.elasticmapreduce/spark/install-spark with -x, -v, 1.2.0.a, -g, 

My `/home/hadoop/spark/conf/spark-defaults.conf` looks like: 

```
spark.eventLog.enabled  true
spark.eventLog.dir      hdfs:///spark-logs
spark.executor.extraJavaOptions         -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70 -XX:MaxHeapFreeRatio=70
spark.metrics.conf      /home/hadoop/spark/conf/ganglia.metrics.properties
spark.executor.instances
spark.executor.cores
spark.executor.memory   10112M
spark.default.parallelism       *
```

The last line contains an invalid value (`spark.default.parallelism       *`).  When I try to run a Spark job, I get:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "*"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at org.apache.spark.SparkConf$$anonfun$getInt$2.apply(SparkConf.scala:184)
        at org.apache.spark.SparkConf$$anonfun$getInt$2.apply(SparkConf.scala:184)
        at scala.Option.map(Option.scala:145)
        at org.apache.spark.SparkConf.getInt(SparkConf.scala:184)
        at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend.defaultParallelism(CoarseGrainedSchedulerBackend.scala:271)
        at org.apache.spark.scheduler.TaskSchedulerImpl.defaultParallelism(TaskSchedulerImpl.scala:402)
        at org.apache.spark.SparkContext.defaultParallelism(SparkContext.scala:1455)
        at org.apache.spark.SparkContext.defaultMinPartitions(SparkContext.scala:1462)
        at org.apache.spark.SparkContext.textFile$default$2(SparkContext.scala:539)
        at org.apache.spark.api.java.JavaSparkContext.textFile(JavaSparkContext.scala:184)
```

It looks like the issue is in `maximize-spark-default-config`.  When I download it to my master and run it manually, there are some issues:

```
+ VCOREREFERENCE=http://support.elasticmapreduce.s3.amazonaws.com/spark/vcorereference.tsv
+ CONFIGURESPARK=http://support.elasticmapreduce.s3.amazonaws.com/spark/configure-spark.bash
+ echo 'Configuring Spark default configuration to the max memory and vcore setting given configured number of cores nodes at cluster creation'
Configuring Spark default configuration to the max memory and vcore setting given configured number of cores nodes at cluster creation
+ /usr/share/aws/emr/scripts/configure-hadoop -y yarn.scheduler.minimum-allocation-mb=256
Processing default file /home/hadoop/conf/yarn-site.xml with overwrite yarn.scheduler.minimum-allocation-mb=256
'yarn.scheduler.minimum-allocation-mb': new value '256' overwriting '256'
Saved /home/hadoop/conf/yarn-site.xml with overwrites. Original saved to /home/hadoop/conf/yarn-site.xml.old
++ grep /mnt/var/lib/info/job-flow.json -e CORE -A 4
++ grep -e requestedInstanceCount
++ cut -d: -f2
++ sed 's/\s\+//g'
+ NUM_CORE_NODES=
+ '[' -lt 2 ']'
./f: line 27: [: -lt: unary operator expected
++ grep /mnt/var/lib/info/job-flow.json -e CORE -A 4
++ grep -e instanceType
++ cut '-d"' -f4
++ sed 's/\s\+//g'
+ CORE_INSTANCE_TYPE=
+ '[' == '' ']'
./f: line 35: [: ==: unary operator expected
+ wget http://support.elasticmapreduce.s3.amazonaws.com/spark/vcorereference.tsv
--2015-01-12 10:58:39--  http://support.elasticmapreduce.s3.amazonaws.com/spark/vcorereference.tsv
Resolving support.elasticmapreduce.s3.amazonaws.com (support.elasticmapreduce.s3.amazonaws.com)... 54.231.32.217
Connecting to support.elasticmapreduce.s3.amazonaws.com (support.elasticmapreduce.s3.amazonaws.com)|54.231.32.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 470 [text/tab-separated-values]
Saving to: ‘vcorereference.tsv.3’

vcorereference.tsv.3                                            100%[========================================================================================================================================================>]     470  --.-KB/s   in 0s

2015-01-12 10:58:40 (57.0 MB/s) - ‘vcorereference.tsv.3’ saved [470/470]

++ grep vcorereference.tsv -e
++ cut -f2
grep: option requires an argument -- 'e'
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
+ NUM_VCORES=
++ grep /home/hadoop/conf/yarn-site.xml -e 'yarn\.scheduler\.maximum-allocation-mb'
++ sed 's/.*<value>\(.*\).*<\/value>.*/\1/g'
+ MAX_YARN_MEMORY=11520
++ expr 11520 - 1024 - 384
+ EXEC_MEMORY=10112
+ EXEC_MEMORY+=M
+ echo 'num vcores '
num vcores
+ echo 'num core nodes '
num core nodes
++ expr '*'
+ PARALLEL='*'
+ echo 'parallel *'
parallel *
+ wget http://support.elasticmapreduce.s3.amazonaws.com/spark/configure-spark.bash
--2015-01-12 10:58:40--  http://support.elasticmapreduce.s3.amazonaws.com/spark/configure-spark.bash
Resolving support.elasticmapreduce.s3.amazonaws.com (support.elasticmapreduce.s3.amazonaws.com)... 54.231.32.217
Connecting to support.elasticmapreduce.s3.amazonaws.com (support.elasticmapreduce.s3.amazonaws.com)|54.231.32.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 584 [binary/octet-stream]
Saving to: ‘configure-spark.bash.3’

configure-spark.bash.3                                          100%[========================================================================================================================================================>]     584  --.-KB/s   in 0s

2015-01-12 10:58:40 (69.6 MB/s) - ‘configure-spark.bash.3’ saved [584/584]

+ exit 0
```

(btw, I commented out the call to configure-spark.bash at the end).

It looks like:
* `NUM_CORE_NODES` is set to empty string (expected?)
* syntax error on  `'[' -lt 2 ']'`
    `line 27: [: -lt: unary operator expected`
* another on `+ '[' == '' ']'`
   `line 35: [: ==: unary operator expected`
* `NUM_VCORES` is an empty string (expected?)
* `PARALLEL` is set to `'*'` - this is what is causing my current issue

I can hack this for now, but it'd be great to see a fix this pushed out (or clarification if I'm doing something wrong).

**Comment by dunajevas** [comment]
https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/maximize-spark-default-config script does grep statements wrong for example
NUM_CORE_NODES=$(grep /mnt/var/lib/info/job-flow.json -e "CORE" -A 4 | grep -e requestedInstanceCount | cut -d':' -f2 | sed  's/\s\+//g')
does not work since Core is not in camel case, at least in ami 3.3.1

**Comment by jonchase** [comment]
This works on 3.3.1 for NUM_CORE_NODES:

  "instanceGroupName": "core",
      "instanceRole": "Core",
      "marketType": "Spot",
      "instanceType": "m3.2xlarge",
      "requestedInstanceCount": 10,
      "bidPrice": ".25"


grep /mnt/var/lib/info/job-flow.json -i -e "CORE" -A 4 | grep -e requestedInstanceCount | cut -d':' -f2 | sed  's/\s\+//g' | cut -d',' -f1
10

**Comment by dunajevas** [comment]
![core](https://cloud.githubusercontent.com/assets/1411952/5741050/689fd28c-9c11-11e4-9e3f-fd4287d765f0.jpg)

**Comment by jonchase** [comment]
I started a new cluster and set the instanceGroupName for the core group to 'CORE' and that worked better, but it's still messed up.  Then it grabs the trailing comma when getting the requestedInstanceCount (like "1,") - which is why I added the "cut -d',' -f1" to the end of my command.

**Comment by christopherbozeman** [comment]
Thank you for the report and discussion.   This issue is addressed in https://github.com/awslabs/emr-bootstrap-actions/pull/40.   These changes to script maximize-spark-default-config are now live at s3://support.elasticmapreduce/spark/.

**Comment by jonchase** [comment]
Changes look good to me.  thx!!

**Comment by christopherbozeman** [comment]
jonchase - please close issue if resolved.  Thanks!

**Comment by jonchase** [comment]
Looks like someone beat me to closing it.  Works as expected now, thanks.
