### ISSUE TITLE
Spark built with avro-mapred for hadoop1 instead of hadoop2?

### ISSUE THREAD

**Issue by wongelz** [awslabs/emr-bootstrap-actions#39]
Running spark on AMI 3.x (hadoop 2.x) I get the following exception trying to read any avro files. According to https://issues.apache.org/jira/browse/SPARK-3039 this should have been fixed in 1.2.0, so I suspect 1.2.0.a didn't include this fix?

java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
	at org.apache.avro.mapreduce.AvroKeyInputFormat.createRecordReader(AvroKeyInputFormat.java:47)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:133)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:107)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wongelz** [comment]
The offending class comes from in /home/hadoop/.versions/hive-0.13.1/lib/hive-exec-0.13.1.jar (which gets copied to /home/hadoop/classpath/emr). This has been fixed in hive 0.14 (https://issues.apache.org/jira/browse/HIVE-7712).

**Comment by christopherbozeman** [comment]
This is fixed with https://github.com/awslabs/emr-bootstrap-actions/pull/53 which is live in the default Spark install script.  The script does a cleaner job placing into the classpath only the jars it really needs so the bug in hive*.jar .

Tested with https://github.com/databricks/spark-avro.
