### ISSUE TITLE
Trouble with YARN log aggregation setup

### ISSUE THREAD

**Issue by jkleckner** [awslabs/emr-bootstrap-actions#48]
I set up YARN log aggregation as described here: https://spark.apache.org/docs/1.1.1/running-on-yarn.html
by using a boostrap step in ```aws emr create-cluster``` like this:
```
Name="Aggregate logs",Path=s3://elasticmapreduce/bootstrap-actions/configure-hadoop,\
Args=[\
"-y","yarn.log-aggregation-enable=true",\
"-y","yarn.log-aggregation.retain-seconds=36000",\
"-y","yarn.log-aggregation.retain-check-interval-seconds=3600",\
"-y","yarn.nodemanager.remote-app-log-dir=s3://somewriteablebucketofmine",\
] \
```
Nothing gets stored in the bucket and if I try to invoke yarn to display the logs, I get the following:
```bash
$ yarn logs -applicationId application_1421712553870_0003
15/01/20 00:18:40 INFO client.RMProxy: Connecting to ResourceManager at /10.168.80.68:9022
Exception in thread "main" org.apache.hadoop.fs.UnsupportedFileSystemException: No AbstractFileSystem for scheme: s3
        at org.apache.hadoop.fs.AbstractFileSystem.createFileSystem(AbstractFileSystem.java:154)
        at org.apache.hadoop.fs.AbstractFileSystem.get(AbstractFileSystem.java:242)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:333)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:330)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.fs.FileContext.getAbstractFileSystem(FileContext.java:330)
        at org.apache.hadoop.fs.FileContext.getFSofPath(FileContext.java:322)
        at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:85)
        at org.apache.hadoop.fs.FileContext.listStatus(FileContext.java:1388)
        at org.apache.hadoop.yarn.logaggregation.LogCLIHelpers.dumpAllContainersLogs(LogCLIHelpers.java:112)
        at org.apache.hadoop.yarn.client.cli.LogsCLI.run(LogsCLI.java:137)
        at org.apache.hadoop.yarn.client.cli.LogsCLI.main(LogsCLI.java:199)
```
This sounds suspiciously like the issue described here: http://stackoverflow.com/a/26491972/541202

I tried switching to hdfs as in the following, but nothing showed up in the ```hdfs://tmp/logs``` location:
```bash
Name="Aggregate logs",Path=s3://elasticmapreduce/bootstrap-actions/configure-hadoop,\
Args=[\
"-y","yarn.log-aggregation-enable=true",\
"-y","yarn.log-aggregation.retain-seconds=36000",\
"-y","yarn.log-aggregation.retain-check-interval-seconds=3600",\
"-y","yarn.nodemanager.remote-app-log-dir=hdfs://tmp/logs",\
] \
```
Suggestions?

**Comment by jkleckner** [comment]
I found a typo and it is now aggregating into s3.
I will try again to aggregate into hdfs and report back if issues and close if not.

**Comment by jkleckner** [comment]
Fixed.

**Comment by hjdesai2** [comment]
@jkleckner Can you let me know the typo.. I am running into the same issue for S3 ??

**Comment by jkleckner** [comment]
@hjdesai2 Sorry, it didn't make it into my git history.

**Comment by hjdesai2** [comment]
@jkleckner : I am having same isssues, so S3 is not an abstract file system right ? , how did you solve the issue.. can I get the property details ?

```
<property><name>yarn.log-aggregation-enable</name><value>true</value></property>
<property><name>yarn.log-aggregation.retain-seconds</name><value>-1</value></property>
<property><name>yarn.log-aggregation.retain-check-interval-seconds</name><value>3000</value></property>
<property><name>yarn.nodemanager.remote-app-log-dir</name><value>s3://mybucket/logs</value></property>```

**Comment by jkleckner** [comment]
@hjdesai2 , Here is the script (with some obvious redactions and variables) that I used with pre-3.8 AMI versions.  Hope it is useful:
```
aws emr create-cluster \
  --region us-east-1 \
  --name ${stackName} \
  --instance-groups '[
    { "Name": "spark_master", "InstanceCount": 1, "InstanceGroupType": "MASTER",                   "InstanceType": "m3.'${stackSize}'" },
    { "Name": "spark_core",   "InstanceCount": 1, "InstanceGroupType": "CORE",                     "InstanceType": "m3.'${stackSize}'" },
    { "Name": "spark_slave",  "InstanceCount": 1, "InstanceGroupType": "TASK",   '"${useSpot[*]}"' "InstanceType": "m3.'${stackSize}'" }
  ]' \
  --no-auto-terminate \
  --ami-version ${amiVersion} \
  --log-uri s3://path-to-bucket-for logs \
  --ec2-attributes KeyName=key_name,InstanceProfile=EMR-appropriate-role,AvailabilityZone=us-east-1a \
  --service-role=EMR_DefaultRole \
  --no-termination-protected \
  --visible-to-all-users \
  --enable-debugging \
  --tags \
    Name=${stackName} \
    env=dev service=my_service stack=${stackName} \
    creatinguser=jim class=class_axis_value \
  --applications Name=Ganglia \
  --bootstrap-actions \
    Name=InstallSpark,Args="${sparkVersion}-x,-g",Path=s3://support.elasticmapreduce/spark/install-spark \
    Name="Configure HBase for Ganglia",Path=s3://us-east-1.elasticmapreduce/bootstrap-actions/configure-hbase-for-ganglia \
    Name="Aggregate logs",Path=s3://elasticmapreduce/bootstrap-actions/configure-hadoop,\
Args=[\
"-y","yarn.log-aggregation-enable=true",\
"-y","yarn.log-aggregation.retain-seconds=43200",\
"-y","yarn.log-aggregation.retain-check-interval-seconds=1800",\
"-c","hadoop.http.staticuser.user=hadoop"\
] \
  --steps \
    Name=SparkHistoryServer,Jar=s3://elasticmapreduce/libs/script-runner/script-runner.jar,Args=s3://support.elasticmapreduce/spark/start-history-server
```
And I don't suggest that ```staticuser``` setting for anything but development stacks...

This was tested with ```sparkVersion="-v,1.2.1.a,"``` and ```amiVersion="3.5.0"```.

Have moved on a bit since then.

**Comment by hjdesai2** [comment]
@jkleckner Thanks , I am setting the same properties in already created cluster but still not reflecting, do I need to  restart Job Tracker and namenode ?

**Comment by jkleckner** [comment]
@hjdesai2 Those steps are run at create-cluster time for me.  I normally create a new cluster when basic options change because who knows what complexity of updating all the core/slave nodes might exist.
