### ISSUE TITLE
spark-submit fails via script-runner.jar (custom Spark build)

### ISSUE THREAD

**Issue by ericeijkelenboom** [awslabs/emr-bootstrap-actions#91]
Hi

I would like to run a custom Spark build (1.3.1). What I did: 

1. Build Spark 1.3.1 from source, according to your example page (Scala 2.10). 
2. Use custom config.file and launch with -c. 

Funny enough, running ./bin/spark-submit directly from the command line works fine. 

However, when going through Amazon's script-runner.jar (i.e.: hadoop jar /path/to/script-runner.jar /home/hadoop/spark/bin/spark-submit ... etc), I receive the following error:

Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
	at org.apache.spark.deploy.SparkSubmitArguments.parse$1(SparkSubmitArguments.scala:295)
	at org.apache.spark.deploy.SparkSubmitArguments.parseOpts(SparkSubmitArguments.scala:288)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:87)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:105)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Command exiting with ret '1'

Is this something you have seen before?

Thanks, 
Eric

**Comment by christopherbozeman** [comment]
Yes, this is a known issue with 1.3.1 hence why it was not made default yet.  Though, I just resolved the issue today and working on pushing a new version that works with EMR steps as well.

**Comment by christopherbozeman** [comment]
Fixed with build 1.3.1.b. https://github.com/awslabs/emr-bootstrap-actions/pull/93

**Comment by ericeijkelenboom** [comment]
Awesome, thank you!
